from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


output = Path("output/pdf/sunrise_system_report_template.pdf")
output.parent.mkdir(parents=True, exist_ok=True)
width, height = A4
pdf = canvas.Canvas(str(output), pagesize=A4)
pdf.setTitle("Sunrise Dental Clinic System Report")

navy = colors.HexColor("#062B4D")
teal = colors.HexColor("#0F766E")
slate = colors.HexColor("#64748B")
ink = colors.HexColor("#0F172A")
line = colors.HexColor("#E2E8F0")
soft = colors.HexColor("#F8FAFC")

pdf.setFillColor(navy)
pdf.rect(0, height - 120, width, 120, fill=1, stroke=0)
pdf.setFillColor(colors.white)
pdf.setFont("Helvetica-Bold", 22)
pdf.drawString(42, height - 55, "SUNRISE DENTAL CLINIC")
pdf.setFont("Helvetica", 10)
pdf.drawString(42, height - 78, "SYSTEM SUMMARY REPORT")
pdf.drawRightString(width - 42, height - 78, "ADMIN REPORT")

pdf.setFillColor(ink)
pdf.setFont("Helvetica-Bold", 15)
pdf.drawString(42, height - 162, "Clinic overview")
pdf.setFillColor(slate)
pdf.setFont("Helvetica", 9)
pdf.drawString(42, height - 180, "Operational totals at the time this report was generated.")

cards = [("PATIENTS", "0"), ("APPOINTMENTS", "0"), ("PAID BILLS", "0"), ("OPEN TICKETS", "0")]
card_width = (width - 105) / 4
x = 42
for label, value in cards:
    pdf.setFillColor(soft)
    pdf.roundRect(x, height - 285, card_width, 76, 8, fill=1, stroke=0)
    pdf.setFillColor(slate)
    pdf.setFont("Helvetica-Bold", 8)
    pdf.drawString(x + 12, height - 231, label)
    pdf.setFillColor(ink)
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(x + 12, height - 266, value)
    x += card_width + 7

pdf.setFillColor(colors.HexColor("#F0FDFA"))
pdf.roundRect(42, height - 380, width - 84, 62, 8, fill=1, stroke=0)
pdf.setFillColor(teal)
pdf.setFont("Helvetica-Bold", 10)
pdf.drawString(58, height - 343, "TOTAL REVENUE")
pdf.setFont("Helvetica-Bold", 20)
pdf.drawRightString(width - 58, height - 358, "Rs. 0.00")

pdf.setFillColor(ink)
pdf.setFont("Helvetica-Bold", 12)
pdf.drawString(42, height - 425, "Report notes")
pdf.setStrokeColor(line)
pdf.line(42, height - 437, width - 42, height - 437)
pdf.setFillColor(slate)
pdf.setFont("Helvetica", 9)
pdf.drawString(42, height - 460, "Counts reflect current database records and active support requests.")
pdf.drawString(42, height - 478, "Revenue is calculated from all saved billing records.")

pdf.setFillColor(slate)
pdf.setFont("Helvetica", 8)
pdf.drawString(42, 42, "Generated by Sunrise Dental Clinic Management System")
pdf.drawRightString(width - 42, 42, "Confidential - Administrator use only")
pdf.save()
print(output.resolve())
